"""Small dependency-free browser surface for the first real-material Gate."""
from fastapi.responses import HTMLResponse

M1_GATE_HTML = r'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Content OS · 第一真实素材 Gate</title><style>
body{font:15px system-ui,sans-serif;max-width:1180px;margin:1.5rem auto;padding:0 1rem;color:#202124;background:#f7f8fa}section,.scene{background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:1rem;margin:1rem 0}label{display:block;margin:.5rem 0}input,textarea,select{box-sizing:border-box;width:100%;padding:.55rem;border:1px solid #bbc2cc;border-radius:6px}textarea{min-height:100px}button{padding:.5rem .75rem;border:1px solid #8993a1;border-radius:6px;background:#fff;cursor:pointer;margin:.25rem}.primary{background:#1769e0;color:#fff;border-color:#1769e0}.primary:disabled,button:disabled{opacity:.45;cursor:not-allowed;filter:grayscale(1)}.muted{color:#667085}.error{color:#b42318}.ok{color:#067647}.candidate{border:1px solid #e3e7ed;border-radius:8px;padding:.65rem;margin:.5rem 0}.candidate.selected{border:2px solid #1769e0}video{max-width:250px;max-height:280px;background:#111}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:.75rem}.pill{display:inline-block;background:#eef2ff;padding:.2rem .45rem;border-radius:1rem;font-size:.85em}
</style></head><body><h1>第一真实素材 Gate</h1><p class="muted">本地验收面：项目 → 文案/主题 → ScenePlan → Top‑1/Top‑3 素材 → 人工替换 → VideoSpec。不会用假数据冒充供应商结果。</p>
<section><h2>1. 测试项目</h2><select id="project"><option value="">选择已有项目…</option></select><div class="grid"><label>标题<input id="title" placeholder="例如：第一条真实主题"></label><label>创作者<input id="creator" value="本地创作者"></label></div><label>主题<input id="topic" placeholder="选题主题"></label><button id="create">创建项目</button><span id="pmsg" class="muted"></span></section>
<section><h2>2. 输入脚本或主题并生成 ScenePlan</h2><textarea id="script" placeholder="输入完整脚本（可留空，使用主题）"></textarea><button id="plan" class="primary">生成 ScenePlan</button><span id="provider" class="muted">检查 provider…</span></section>
<section><h2>3. 匹配与人工审核</h2><div id="scenes" class="muted">尚未生成。</div><button id="route" class="primary" disabled>为全部 Scene 匹配 Top‑3</button></section>
<section><h2>4. 导出渲染输入与 Gate 记录</h2><button id="spec" disabled>生成 VideoSpec</button><button id="render" disabled>渲染并预览/下载</button><button id="export" disabled>导出 Gate JSON</button><label>总耗时（自动计时）<input id="totalElapsed" readonly></label><label>人工操作耗时（首次交互起计）<input id="elapsed" readonly></label><p id="gate" class="muted">替换次数：0 · 已确认 Scene：0</p><div id="rendered"></div><pre id="output"></pre></section>
<script>
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), fmt=n=>`${Math.floor(n/60000)}:${String(Math.floor(n/1000)%60).padStart(2,'0')}.${String(n%1000).padStart(3,'0')}`;
let scenes=[],routes=[],selected={},confirmed={},replacements=0,start=null,manualStart=null,lastSpec=null,renderJobTimer=null,activeProjectId=null,draftSaveChain=Promise.resolve(),draftVersion=0;
function pid(){return $('project').value} function msg(t,err=false){$('pmsg').textContent=t;$('pmsg').className=err?'error':'ok'}
async function json(url,opt){let r=await fetch(url,opt),b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.detail||`请求失败 (${r.status})`);return b}
function draftPayload(){return {script:$('script').value.trim()||null,topic:$('topic').value.trim()||null,scenes,routes,confirmed:Object.values(confirmed),video_spec:lastSpec}}
function saveDraft(){let projectId=pid();if(!projectId||!scenes.length)return;let snapshot=draftPayload();draftSaveChain=draftSaveChain.then(async()=>{let saved=await json(`/projects/${projectId}/draft`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot)});draftVersion=saved.version}).catch(e=>msg(`草稿保存失败：${e.message}`,true))}
async function restoreDraft(projectId){let draft=await json(`/projects/${projectId}/draft`);if(!draft.scenes||!draft.scenes.length)return;scenes=draft.scenes;routes=draft.routes||[];confirmed={};(draft.confirmed||[]).forEach(candidate=>{let index=scenes.findIndex(scene=>scene.id===candidate.scene_plan_id);if(index>=0)confirmed[index]=candidate});lastSpec=draft.video_spec||null;draftVersion=draft.version||0;renderScenes();if(routes.length){renderRoutes();$('export').disabled=false}if(lastSpec){$('output').textContent=JSON.stringify(lastSpec,null,2);$('render').disabled=false}updateGate();msg(`已恢复草稿 v${draftVersion}`)}
async function loadProjects(){let ps=await json('/projects');$('project').innerHTML='<option value="">选择已有项目…</option>'+ps.map(p=>`<option value="${p.id}">${esc(p.title)} · ${esc(p.topic)}</option>`).join('');let saved=localStorage.getItem('content-os-active-project');if(saved&&ps.some(p=>p.id===saved)){$('project').value=saved;activeProjectId=saved;await restoreDraft(saved)}}
function resetWorkflowState(){if(renderJobTimer){clearInterval(renderJobTimer);renderJobTimer=null}scenes=[];routes=[];selected={};confirmed={};replacements=0;start=null;manualStart=null;lastSpec=null;$('scenes').innerHTML='尚未生成。';$('route').disabled=true;$('spec').disabled=true;$('render').disabled=true;$('export').disabled=true;$('rendered').innerHTML='';$('output').textContent='';updateGate()}
async function create(){try{let p=await json('/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('title').value,topic:$('topic').value,creator_name:$('creator').value})});await loadProjects();$('project').value=p.id;activeProjectId=p.id;localStorage.setItem('content-os-active-project',p.id);resetWorkflowState();$('project').value=p.id;msg('项目已创建');}catch(e){msg(e.message,true)}}
function renderScenes(){ $('scenes').innerHTML=scenes.map((s,i)=>`<article class="scene"><h3>Scene ${i+1} · ${esc(s.scene_id)}</h3><p>${esc(s.voice_text)}</p><p class="muted">${fmt(s.duration_target_ms)} · ${esc(s.visual_intent.description||s.visual_intent.action||s.purpose)}</p><div id="cand-${i}">等待匹配…</div></article>`).join('');$('route').disabled=!scenes.length;$('spec').disabled=true;$('render').disabled=true;$('export').disabled=true;updateGate() }
async function plan(){if(!pid()){msg('请先选择或创建项目',true);return}resetWorkflowState();start=Date.now();try{let b=await json(`/projects/${pid()}/scene-plan`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({script:$('script').value.trim()||null,topic:$('topic').value.trim()||null})});scenes=b.scenes;renderScenes();saveDraft();msg('ScenePlan 已生成；若提示 provider 未配置，请配置 BYOK 后重试');}catch(e){msg(e.message,true);if(e.message.includes('not configured'))$('provider').textContent='Scene Planner provider 未配置（没有调用假数据）'}}
function bindClipPreviews(){document.querySelectorAll('video[data-clip-id]').forEach(async video=>{try{let clip=await json(`/clips/${video.dataset.clipId}`),startSeconds=clip.start_ms/1000,endSeconds=clip.end_ms/1000;let seek=()=>{if(video.currentTime<startSeconds||video.currentTime>endSeconds)video.currentTime=startSeconds};video.addEventListener('loadedmetadata',seek);video.addEventListener('timeupdate',()=>{if(video.currentTime>=endSeconds){video.pause();video.currentTime=startSeconds}});if(video.readyState>=1)seek()}catch(e){video.title='无法读取 Clip 区间'}})}
function renderRoutes(){routes.forEach((r,i)=>{let cs=r.candidates||[];$(`cand-${i}`).innerHTML=cs.length?cs.map((c,j)=>`<div class="candidate ${confirmed[i]&&confirmed[i].clip_id===c.clip_id?'selected':''}"><button onclick="choose(${i},${j})">${j===0?'Top‑1':'候选 '+(j+1)}${c.recommended?' · 推荐':''}</button><span class="pill">匹配 ${Number(c.match_score).toFixed(3)}</span><span class="pill">成本 ${c.estimated_cost.amount==null?'未知':esc(c.estimated_cost.amount+' '+c.estimated_cost.currency)}</span><p>${esc((c.why||[]).join('；'))}</p><p class="muted">复用 ${c.reuse_count} 次 · ${c.requires_capture?'需补拍':'真实素材'}${confirmed[i]?.clip_id===c.clip_id?' · 已确认':''}</p>${c.clip_id?`<video controls preload="metadata" data-clip-id="${esc(c.clip_id)}" src="/clips/${c.clip_id}/media"></video>`:''}</div>`).join(''):'<p class="error">无候选或 provider 未配置。</p>';});bindClipPreviews()}
async function route(){try{routes=await json(`/projects/${pid()}/asset-routes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenes,max_candidates:3})});selected={};confirmed={};lastSpec=null;$('spec').disabled=true;$('render').disabled=true;$('output').textContent='';$('rendered').innerHTML='';renderRoutes();$('export').disabled=false;saveDraft();updateGate()}catch(e){msg(e.message,true);if(e.message.includes('not configured'))$('provider').textContent='Embedding provider 未配置（没有调用假数据）'}}
function hasAllSelections(){return scenes.length>0&&scenes.every((_,i)=>confirmed[i]&&confirmed[i].clip_id&&!confirmed[i].requires_capture)}
function choose(i,j){if(!manualStart)manualStart=Date.now();let c=routes[i].candidates[j],old=confirmed[i];if(old&&old.clip_id!==c.clip_id&&old.clip_id===routes[i].candidates[0]?.clip_id)replacements++;selected[i]=c;confirmed[i]=c;lastSpec=null;$('output').textContent='';$('render').disabled=true;renderRoutes();saveDraft();updateGate()}
function isConfirmed(candidate){return Boolean(candidate?.clip_id&&!candidate.requires_capture)}
function updateGate(){let n=scenes.length,top1=scenes.reduce((a,_,i)=>a+(isConfirmed(confirmed[i])&&confirmed[i].clip_id===routes[i]?.candidates?.[0]?.clip_id?1:0),0),coverage=scenes.reduce((a,_,i)=>a+(isConfirmed(confirmed[i])?1:0),0),user=scenes.reduce((a,_,i)=>a+(isConfirmed(confirmed[i])&&confirmed[i].source_kind==='user_asset'?1:0),0);$('gate').textContent=`替换次数：${replacements} · 已确认 Scene：${coverage}/${n} · Top‑1 已确认：${top1}/${n}`;$('elapsed').value=manualStart?Math.round((Date.now()-manualStart)/1000)+' 秒':'尚未开始';$('totalElapsed').value=start?Math.round((Date.now()-start)/1000)+' 秒':'尚未开始';$('spec').disabled=!hasAllSelections()}
async function spec(){try{let b=await json(`/projects/${pid()}/video-spec`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenes,selections:Object.values(confirmed),explicit_scene_ids:Object.keys(confirmed).map(i=>scenes[i]?.id).filter(Boolean)})});lastSpec=b;$('output').textContent=JSON.stringify(b,null,2);$('render').disabled=false;saveDraft();msg('VideoSpec 已生成，可交给渲染器');}catch(e){msg(e.message,true)}}
function exportGate(){let n=scenes.length,top1=scenes.reduce((a,_,i)=>a+(isConfirmed(confirmed[i])&&confirmed[i].clip_id===routes[i]?.candidates?.[0]?.clip_id?1:0),0),coverage=scenes.reduce((a,_,i)=>a+(isConfirmed(confirmed[i])?1:0),0),user=scenes.reduce((a,_,i)=>a+(isConfirmed(confirmed[i])&&confirmed[i].source_kind==='user_asset'?1:0),0),unknown=routes.reduce((a,r)=>a+(r.candidates||[]).filter(c=>c.estimated_cost.amount==null).length,0);let rec={recorded_at:new Date().toISOString(),project_id:pid(),script:$('script').value,topic:$('topic').value,scenes,routes,selected:confirmed,replacements,replacement_count:replacements,scene_count:n,top1_acceptance_count:top1,top1_acceptance_rate:n?top1/n:0,top3_coverage_count:coverage,top3_coverage_rate:n?coverage/n:0,selected_user_asset_count:user,selected_user_asset_rate:n?user/n:0,elapsed_seconds:start?Math.round((Date.now()-start)/1000):0,total_elapsed_seconds:start?Math.round((Date.now()-start)/1000):0,manual_elapsed_seconds:manualStart?Math.round((Date.now()-manualStart)/1000):0,unknown_cost_count:unknown,video_spec:lastSpec};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(rec,null,2)],{type:'application/json'}));a.download='m1-gate-record.json';a.click()}
const RENDER_ACTIVE_STATUSES=['pending','running'];
function showRenderJob(j){let status=esc(j.status||'unknown');if(j.status==='completed'&&j.preview_url){$('render').disabled=false;$('rendered').innerHTML=`<p class="ok">渲染完成</p><p><a href="${esc(j.preview_url)}" target="_blank">预览</a> <a href="${esc(j.download_url||j.preview_url)}" download>下载</a></p>`;msg('渲染完成');return}if(j.status==='failed'){ $('render').disabled=false;$('rendered').innerHTML=`<p class="error">渲染失败：${esc(j.error_message||'本地渲染失败')}</p>`;msg('渲染失败',true);return}if(j.status==='cancelled')$('render').disabled=false;$('rendered').innerHTML=`<p class="muted">渲染任务状态：${RENDER_ACTIVE_STATUSES.includes(j.status)?status:'未知状态'}（第 ${esc(j.attempt||0)} 次尝试）</p>`}
async function pollRenderJob(id){if(renderJobTimer)clearInterval(renderJobTimer);const poll=async()=>{try{let j=await json(`/jobs/${id}`);showRenderJob(j);if(['completed','failed','cancelled'].includes(j.status)){clearInterval(renderJobTimer);renderJobTimer=null}}catch(e){clearInterval(renderJobTimer);renderJobTimer=null;msg(`查询渲染任务失败：${e.message}`,true)}};await poll();renderJobTimer=setInterval(poll,1500)}
async function render(){if(!lastSpec){msg('请先生成 VideoSpec',true);return}if(renderJobTimer){clearInterval(renderJobTimer);renderJobTimer=null}try{$('render').disabled=true;$('rendered').innerHTML='<p class="muted">正在提交渲染任务…</p>';let b=await json(`/projects/${pid()}/render-jobs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({video_spec:lastSpec,idempotency_key:`m1-gate-${pid()}-${Date.now()}`})});showRenderJob(b);pollRenderJob(b.id)}catch(e){$('render').disabled=false;msg(`渲染任务不可用：${e.message}`,true)}}
async function selectProject(){let next=pid();if(next===activeProjectId)return;activeProjectId=next;localStorage.setItem('content-os-active-project',next);resetWorkflowState();if(!next)return;let project=[...$('project').options].find(option=>option.value===next);if(project){let label=project.textContent.split(' · ');$('title').value=label[0]||'';$('topic').value=label.slice(1).join(' · ')||''}try{await restoreDraft(next)}catch(e){msg(`草稿读取失败：${e.message}`,true)}}
$('create').onclick=create;$('plan').onclick=plan;$('route').onclick=route;$('spec').onclick=spec;$('render').onclick=render;$('export').onclick=exportGate;$('project').onchange=selectProject;setInterval(updateGate,1000);loadProjects().catch(e=>msg(e.message,true));
</script></body></html>'''

def m1_gate_page() -> HTMLResponse:
    return HTMLResponse(M1_GATE_HTML)
