"""Small dependency-free browser surface for the first real-material Gate."""
from fastapi.responses import HTMLResponse

M1_GATE_HTML = r'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Content OS · 第一真实素材 Gate</title><style>
body{font:15px system-ui,sans-serif;max-width:1180px;margin:1.5rem auto;padding:0 1rem;color:#202124;background:#f7f8fa}section,.scene{background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:1rem;margin:1rem 0}label{display:block;margin:.5rem 0}input,textarea,select{box-sizing:border-box;width:100%;padding:.55rem;border:1px solid #bbc2cc;border-radius:6px}textarea{min-height:100px}button{padding:.5rem .75rem;border:1px solid #8993a1;border-radius:6px;background:#fff;cursor:pointer;margin:.25rem}.primary{background:#1769e0;color:#fff;border-color:#1769e0}.primary:disabled,button:disabled{opacity:.45;cursor:not-allowed;filter:grayscale(1)}.muted{color:#667085}.error{color:#b42318}.ok{color:#067647}.candidate{border:1px solid #e3e7ed;border-radius:8px;padding:.65rem;margin:.5rem 0}.candidate.selected{border:2px solid #1769e0}video{max-width:250px;max-height:280px;background:#111}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:.75rem}.pill{display:inline-block;background:#eef2ff;padding:.2rem .45rem;border-radius:1rem;font-size:.85em}
</style></head><body><h1>第一真实素材 Gate</h1><p class="muted">本地验收面：项目 → 文案/主题 → ScenePlan → Top‑1/Top‑3 素材 → 人工替换 → VideoSpec。不会用假数据冒充供应商结果。</p>
<section><h2>1. 测试项目</h2><select id="project"><option value="">选择已有项目…</option></select><div class="grid"><label>标题<input id="title" placeholder="例如：NASCAR Race Today · 第一条真实素材"></label><label>创作者<input id="creator" value="本地创作者"></label></div><label>主题<input id="topic" placeholder="选题主题"></label><button id="create">创建项目</button><span id="pmsg" class="muted"></span></section>
<section><h2>2. 输入脚本或主题并生成 ScenePlan</h2><textarea id="script" placeholder="输入完整脚本（可留空，使用主题）"></textarea><button id="plan" class="primary">生成 ScenePlan</button><span id="provider" class="muted">检查 provider…</span></section>
<section><h2>3. 匹配与人工审核</h2><div id="scenes" class="muted">尚未生成。</div><button id="route" class="primary" disabled>为全部 Scene 匹配 Top‑3</button></section>
<section><h2>4. 导出渲染输入与 Gate 记录</h2><button id="spec" disabled>生成 VideoSpec</button><button id="export" disabled>导出 Gate JSON</button><label>人工耗时（自动计时）<input id="elapsed" readonly></label><p id="gate" class="muted">替换次数：0 · 已选 Scene：0</p><pre id="output"></pre></section>
<script>
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), fmt=n=>`${Math.floor(n/60000)}:${String(Math.floor(n/1000)%60).padStart(2,'0')}.${String(n%1000).padStart(3,'0')}`;
let scenes=[],routes=[],selected={},replacements=0,start=null,lastSpec=null;
function pid(){return $('project').value} function msg(t,err=false){$('pmsg').textContent=t;$('pmsg').className=err?'error':'ok'}
async function json(url,opt){let r=await fetch(url,opt),b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.detail||`请求失败 (${r.status})`);return b}
async function loadProjects(){let ps=await json('/projects');$('project').innerHTML='<option value="">选择已有项目…</option>'+ps.map(p=>`<option value="${p.id}">${esc(p.title)} · ${esc(p.topic)}</option>`).join('');}
async function create(){try{let p=await json('/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('title').value,topic:$('topic').value,creator_name:$('creator').value})});await loadProjects();$('project').value=p.id;msg('项目已创建');}catch(e){msg(e.message,true)}}
function renderScenes(){ $('scenes').innerHTML=scenes.map((s,i)=>`<article class="scene"><h3>Scene ${i+1} · ${esc(s.scene_id)}</h3><p>${esc(s.voice_text)}</p><p class="muted">${fmt(s.duration_target_ms)} · ${esc(s.visual_intent.description||s.visual_intent.action||s.purpose)}</p><div id="cand-${i}">等待匹配…</div></article>`).join('');$('route').disabled=!scenes.length;$('spec').disabled=true;$('export').disabled=true;updateGate() }
async function plan(){if(!pid()){msg('请先选择或创建项目',true);return}start=Date.now();replacements=0;lastSpec=null;try{let b=await json(`/projects/${pid()}/scene-plan`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({script:$('script').value.trim()||null,topic:$('topic').value.trim()||null})});scenes=b.scenes;routes=[];selected={};renderScenes();msg('ScenePlan 已生成；若提示 provider 未配置，请配置 BYOK 后重试');}catch(e){msg(e.message,true);if(e.message.includes('not configured'))$('provider').textContent='Scene Planner provider 未配置（没有调用假数据）'}}
function renderRoutes(){routes.forEach((r,i)=>{let cs=r.candidates||[];$(`cand-${i}`).innerHTML=cs.length?cs.map((c,j)=>`<div class="candidate ${selected[i]&&selected[i].clip_id===c.clip_id?'selected':''}"><button onclick="choose(${i},${j})">${j===0?'Top‑1':'候选 '+(j+1)}${c.recommended?' · 推荐':''}</button><span class="pill">匹配 ${Number(c.match_score).toFixed(3)}</span><span class="pill">成本 ${c.estimated_cost.amount==null?'未知':esc(c.estimated_cost.amount+' '+c.estimated_cost.currency)}</span><p>${esc((c.why||[]).join('；'))}</p><p class="muted">复用 ${c.reuse_count} 次 · ${c.requires_capture?'需补拍':'真实素材'}</p>${c.clip_id?`<video controls preload="metadata" src="/clips/${c.clip_id}/media"></video>`:''}</div>`).join(''):'<p class="error">无候选或 provider 未配置。</p>'})}
async function route(){try{routes=await json(`/projects/${pid()}/asset-routes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenes,max_candidates:3})});routes.forEach((r,i)=>{let cs=r.candidates||[];let preferred=cs.find(c=>c.recommended)||cs[0];if(preferred)selected[i]=preferred});renderRoutes();$('export').disabled=false;updateGate()}catch(e){msg(e.message,true);if(e.message.includes('not configured'))$('provider').textContent='Embedding provider 未配置（没有调用假数据）'}}
function hasAllSelections(){return scenes.length>0&&scenes.every((_,i)=>selected[i]&&selected[i].clip_id)}
function choose(i,j){let c=routes[i].candidates[j],old=selected[i];if(old&&old.clip_id!==c.clip_id&&old.clip_id===routes[i].candidates[0]?.clip_id)replacements++;selected[i]=c;renderRoutes();updateGate()}
function updateGate(){let n=scenes.length,top1=scenes.reduce((a,_,i)=>a+(selected[i]?.clip_id===routes[i]?.candidates?.[0]?.clip_id?1:0),0),coverage=scenes.reduce((a,_,i)=>a+(selected[i]?1:0),0),user=scenes.reduce((a,_,i)=>a+(selected[i]?.source_kind==='user_asset'?1:0),0);$('gate').textContent=`替换次数：${replacements} · 已选 Scene：${coverage}/${n}`;$('elapsed').value=start?Math.round((Date.now()-start)/1000)+' 秒':'尚未开始';$('spec').disabled=!hasAllSelections()}
async function spec(){try{let b=await json(`/projects/${pid()}/video-spec`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenes,selections:Object.values(selected),explicit_scene_ids:[]})});lastSpec=b;$('output').textContent=JSON.stringify(b,null,2);msg('VideoSpec 已生成，可交给渲染器');}catch(e){msg(e.message,true)}}
function exportGate(){let n=scenes.length,top1=scenes.reduce((a,_,i)=>a+(selected[i]?.clip_id===routes[i]?.candidates?.[0]?.clip_id?1:0),0),coverage=scenes.reduce((a,_,i)=>a+(routes[i]?.candidates?.length?1:0),0),user=scenes.reduce((a,_,i)=>a+(selected[i]?.source_kind==='user_asset'?1:0),0),unknown=routes.reduce((a,r)=>a+(r.candidates||[]).filter(c=>c.estimated_cost.amount==null).length,0);let rec={recorded_at:new Date().toISOString(),project_id:pid(),script:$('script').value,topic:$('topic').value,scenes,routes,selected,replacements,replacement_count:replacements,scene_count:n,top1_acceptance_count:top1,top1_acceptance_rate:n?top1/n:0,top3_coverage_count:coverage,top3_coverage_rate:n?coverage/n:0,selected_user_asset_count:user,selected_user_asset_rate:n?user/n:0,elapsed_seconds:start?Math.round((Date.now()-start)/1000):0,unknown_cost_count:unknown,video_spec:lastSpec};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(rec,null,2)],{type:'application/json'}));a.download='m1-gate-record.json';a.click()}
$('create').onclick=create;$('plan').onclick=plan;$('route').onclick=route;$('spec').onclick=spec;$('export').onclick=exportGate;setInterval(updateGate,1000);loadProjects().catch(e=>msg(e.message,true));
</script></body></html>'''

def m1_gate_page() -> HTMLResponse:
    return HTMLResponse(M1_GATE_HTML)
