"""Interim S1 workspace shell backed by the existing FastAPI APIs.

This page is intentionally dependency-free while the R1 React/Vite surface is
migrated incrementally. It is a user-flow shell, not a replacement for the
diagnostic M1 Gate or for the eventual production UI.
"""
from fastapi.responses import HTMLResponse


WORKSPACE_HTML = r'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Content OS · Workspace</title><style>
body{font:15px system-ui,sans-serif;max-width:1180px;margin:1.5rem auto;padding:0 1rem;color:#202124;background:#f7f8fa}section,.asset,.project{background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:1rem;margin:1rem 0}label{display:block;margin:.55rem 0}input,textarea,select{box-sizing:border-box;width:100%;padding:.55rem;border:1px solid #bbc2cc;border-radius:6px}textarea{min-height:70px}button{padding:.5rem .75rem;border:1px solid #8993a1;border-radius:6px;background:#fff;cursor:pointer;margin:.25rem}.primary{background:#1769e0;color:#fff;border-color:#1769e0}.muted{color:#667085}.error{color:#b42318}.ok{color:#067647}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:.75rem}.row{display:flex;gap:.5rem;align-items:end;flex-wrap:wrap}.row>*{flex:1}.asset small{color:#667085}
</style></head><body><h1>Content OS Workspace</h1><p class="muted">R1 单用户工作区：先确认 IP 资料，再把本地素材按用途分组，最后从主题进入可恢复草稿。外部 Provider 状态不会被假数据掩盖。</p>
<section><h2>运行能力检查</h2><p class="muted">只检查本机依赖和运行时配置，不发送 Provider 请求，不显示或保存密钥。</p><div id="runtime-status">正在检查…</div><button id="refresh-runtime">重新检查</button></section>
<section><h2>运行预算（默认全局）</h2><p class="muted">Provider 调用必须先预留预算；未知价格不会默认为零。失败/重试记录仍保留并参与上限判断。</p><div class="grid"><label>金额上限（USD，可留空）<input id="budget-max-amount" inputmode="decimal"></label><label>调用次数上限（可留空）<input id="budget-max-calls" inputmode="numeric"></label><label><input id="budget-allow-unknown" type="checkbox" style="width:auto"> 允许未知价格（需明确承担对账风险）</label></div><button id="save-budget" class="primary">保存预算</button><span id="budget-status" class="muted"></span></section>
<section><h2>IP 资料（默认档案）</h2><div id="profile-status" class="muted">正在读取…</div><div class="grid"><label>创作者<input id="creator"></label><label>受众<input id="audience"></label><label>专业领域（逗号分隔）<input id="domains"></label><label>主题（逗号分隔）<input id="topics"></label><label>知识（逗号分隔）<textarea id="knowledge"></textarea></label><label>观点（逗号分隔）<textarea id="opinions"></textarea></label><label>表达风格（逗号分隔）<textarea id="style_notes"></textarea></label><label>边界/禁忌（逗号分隔）<textarea id="boundaries"></textarea></label></div><button id="save-profile" class="primary">保存 IP 资料</button><a href="/ip-profile/revisions">查看版本记录</a></section>
<section><h2>本地素材导入</h2><p class="muted">输入 Windows 本地文件或目录路径；系统会自动 hash 去重并用 ffprobe 探测，失败可修正路径后重试。</p><div class="grid"><label>文件/目录路径<input id="source-path" placeholder="C:\\Videos\\Inbox"></label><label>授权记录引用<input id="rights-ref" placeholder="creator-owned-2026"></label></div><button id="import-media" class="primary">导入视频或目录</button><span id="import-status" class="muted"></span></section>
<section><h2>本地 Inbox 增量扫描</h2><p class="muted">按需扫描本地目录；重复内容复用已有 Asset，结果区分新导入、已存在和失败，不代表已完成转写/视觉分析。</p><div class="grid"><label>Inbox 文件夹<input id="inbox-source-path" placeholder="C:\\Videos\\Inbox"></label><label>授权记录引用<input id="inbox-rights-ref" placeholder="creator-owned-2026"></label></div><button id="scan-inbox" class="primary">扫描 Inbox</button><span id="inbox-status" class="muted"></span></section>
<section><h2>静态图片/截图导入</h2><p class="muted">导入 PNG、JPEG 或 WebP，作为有来源的截图/图表候选；不会生成或上传到第三方。</p><div class="grid"><label>图片文件或目录<input id="image-source-path" placeholder="C:\\Screenshots"></label><label>授权记录引用<input id="image-rights-ref" placeholder="creator-screen-2026"></label><label>用途<select id="image-source-kind"><option value="screenshot">截图</option><option value="chart">图表</option></select></label></div><button id="import-images" class="primary">导入静态图片</button><span id="image-import-status" class="muted"></span><div id="image-assets"></div></section>
<section><h2>配音/录音导入</h2><p class="muted">导入已有 WAV、MP3、M4A、AAC、FLAC、OGG 或 OPUS；系统探测时长/采样率后保留授权引用，不启用 TTS 或声音克隆。</p><div class="grid"><label>音频文件或目录<input id="audio-source-path" placeholder="C:\\Voice"></label><label>授权记录引用<input id="audio-rights-ref" placeholder="creator-voice-2026"></label><label>语言（可选）<input id="audio-language" placeholder="zh"></label></div><button id="import-audio" class="primary">导入配音/录音</button><span id="audio-import-status" class="muted"></span><div id="audio-assets"></div></section>
<section><h2>新主题 → 草稿</h2><div class="grid"><label>项目标题<input id="project-title" placeholder="一个可复用的项目名称"></label><label>主题<input id="project-topic" placeholder="输入真实主题"></label></div><button id="create-project" class="primary">创建项目并进入 Gate</button><span id="project-status" class="muted"></span><div id="projects">正在读取项目…</div></section>
<section><h2>有来源选题</h2><p class="muted">只记录已有来源的人工、历史内容或账号信号；没有外部信号时不要填写虚构趋势。</p><div class="grid"><label>来源类型<select id="opportunity-source-type"><option value="manual">人工</option><option value="historical_content">历史内容</option><option value="account_signal">账号信号</option></select></label><label>来源引用<input id="opportunity-source-ref" placeholder="note:2026-09-09 或 historical_content:..."/></label><label>标题<input id="opportunity-title"></label><label>观察时间<input id="opportunity-observed-at" type="datetime-local"></label><label>为何适合当前 IP<textarea id="opportunity-fit"></textarea></label><label>内容角度<textarea id="opportunity-angle"></textarea></label><label>不确定性（可选）<textarea id="opportunity-uncertainty"></textarea></label><label>证据引用（逗号分隔）<input id="opportunity-evidence"></label></div><button id="save-opportunity" class="primary">保存选题</button><span id="opportunity-status" class="muted"></span><div id="opportunities"></div></section>
<section><h2>素材用途确认</h2><p class="muted">用途与身份独立于来源类型：本人形象、可用辅助画面、仅参考、暂不使用。</p><div id="assets">正在读取素材…</div></section>
<script>
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),split=s=>String(s||'').split(/[,\n]/).map(v=>v.trim()).filter(Boolean);
async function json(url,opt){let r=await fetch(url,opt),b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.detail||`请求失败 (${r.status})`);return b}
async function loadRuntime(){try{let readiness=await json('/runtime/readiness'),labels={ready:'可用',provider_not_configured:'Provider 未配置',not_developed:'尚未开发',unavailable:'本机不可用'};$('runtime-status').innerHTML=`<strong class="${readiness.runtime_ready?'ok':'muted'}">${readiness.runtime_ready?'runtime 核心链路可启动':'runtime 核心链路尚未就绪'}</strong><div class="grid">${readiness.capabilities.map(c=>`<article class="asset"><strong>${esc(c.key)}</strong><br><span class="${c.status==='ready'?'ok':c.status==='provider_not_configured'?'muted':'error'}">${labels[c.status]||esc(c.status)}</span><br><small>${esc(c.detail)}${c.model?` · model=${esc(c.model)}`:''}</small></article>`).join('')}</div>`}catch(e){$('runtime-status').textContent=e.message;$('runtime-status').className='error'}}
async function loadBudget(){try{let result=await json('/budget'),policy=result.policy||{};$('budget-max-amount').value=policy.max_amount||'';$('budget-max-calls').value=policy.max_calls??'';$('budget-allow-unknown').checked=Boolean(policy.allow_unknown_cost);$('budget-status').textContent=`${result.policy_source==='none'?'尚未设置':`已设置 · 已计 ${result.snapshot.known_amount} ${result.snapshot.currency} · ${result.snapshot.calls} 次调用`}`;if(result.over_budget)$('budget-status').className='error'}catch(e){$('budget-status').textContent=e.message;$('budget-status').className='error'}}
async function saveBudget(){let amount=$('budget-max-amount').value.trim(),calls=$('budget-max-calls').value.trim();try{let result=await json('/budget',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({currency:'USD',max_amount:amount||null,max_calls:calls===''?null:Number(calls),allow_unknown_cost:$('budget-allow-unknown').checked})});$('budget-status').textContent=`预算已保存 · 已计 ${result.snapshot.known_amount} ${result.snapshot.currency} · ${result.snapshot.calls} 次调用`;$('budget-status').className='ok'}catch(e){$('budget-status').textContent=e.message;$('budget-status').className='error'}}
function fill(id,value){$(id).value=Array.isArray(value)?value.join(', '):value||''}
async function loadProfile(){try{let p=await json('/ip-profile');fill('creator',p.creator_name);fill('audience',p.audience);fill('domains',p.domains);fill('topics',p.topics);fill('knowledge',p.knowledge);fill('opinions',p.opinions);fill('style_notes',p.style_notes);fill('boundaries',p.boundaries);$('profile-status').textContent='已加载默认 IP，可集中修改后保存'}catch(e){$('profile-status').textContent=e.message;$('profile-status').className='error'}}
async function saveProfile(){let p={creator_name:$('creator').value.trim(),audience:$('audience').value.trim()||null,domains:split($('domains').value),topics:split($('topics').value),knowledge:split($('knowledge').value),opinions:split($('opinions').value),style_notes:split($('style_notes').value),boundaries:split($('boundaries').value),vocabulary:[],avoided_expressions:[],common_hooks:[],metadata:{}};try{let saved=await json('/ip-profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});fill('creator',saved.creator_name);$('profile-status').textContent='已保存新的 IP 版本';$('profile-status').className='ok'}catch(e){$('profile-status').textContent=e.message;$('profile-status').className='error'}}
async function loadProjects(){let ps=await json('/projects');let entries=[];for(const p of ps){let d=await json(`/projects/${p.id}/draft`);entries.push(`<article class="project"><strong>${esc(p.title)}</strong><p>${esc(p.topic)}</p><small>IP ${esc(p.ip_profile_id)} · 草稿 v${d.version}</small> <a href="/m1-gate">打开 Gate</a></article>`)}$('projects').innerHTML=entries.join('')||'<p class="muted">尚无项目。</p>'}
async function importMedia(){let source_path=$('source-path').value.trim(),authorization_reference=$('rights-ref').value.trim();if(!source_path||!authorization_reference){$('import-status').textContent='请填写路径和授权记录引用';$('import-status').className='error';return}try{let assets=await json('/imports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_path,authorization_reference,recursive:true})});$('import-status').textContent=`已导入 ${assets.length} 个素材（重复内容会复用原记录）`;$('import-status').className='ok';await loadAssets()}catch(e){$('import-status').textContent=e.message;$('import-status').className='error'}}
async function scanInbox(){let source_path=$('inbox-source-path').value.trim(),authorization_reference=$('inbox-rights-ref').value.trim();if(!source_path||!authorization_reference){$('inbox-status').textContent='请填写 Inbox 路径和授权记录引用';$('inbox-status').className='error';return}try{let result=await json('/inbox/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_path,authorization_reference,recursive:true})});$('inbox-status').textContent=`发现 ${result.discovered} 个 · 新导入 ${result.imported} · 已存在 ${result.existing} · 失败 ${result.errors.length}`;$('inbox-status').className=result.errors.length?'error':'ok';await loadAssets()}catch(e){$('inbox-status').textContent=e.message;$('inbox-status').className='error'}}
async function importImages(){let source_path=$('image-source-path').value.trim(),authorization_reference=$('image-rights-ref').value.trim();if(!source_path||!authorization_reference){$('image-import-status').textContent='请填写图片路径和授权记录引用';$('image-import-status').className='error';return}try{let assets=await json('/image-imports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_path,authorization_reference,source_kind:$('image-source-kind').value,recursive:true})});$('image-import-status').textContent=`已导入 ${assets.length} 张静态图片（重复内容会复用原记录）`;$('image-import-status').className='ok';await loadImages()}catch(e){$('image-import-status').textContent=e.message;$('image-import-status').className='error'}}
async function importAudio(){let source_path=$('audio-source-path').value.trim(),authorization_reference=$('audio-rights-ref').value.trim();if(!source_path||!authorization_reference){$('audio-import-status').textContent='请填写音频路径和授权记录引用';$('audio-import-status').className='error';return}try{let assets=await json('/audio-imports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_path,authorization_reference,language:$('audio-language').value.trim()||null,recursive:true})});$('audio-import-status').textContent=`已导入 ${assets.length} 条音频（重复内容会复用原记录）`;$('audio-import-status').className='ok';await loadAudio()}catch(e){$('audio-import-status').textContent=e.message;$('audio-import-status').className='error'}}
async function createProject(){try{let p=await json('/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('project-title').value.trim(),topic:$('project-topic').value.trim(),creator_name:$('creator').value.trim()})});localStorage.setItem('content-os-active-project',p.id);$('project-status').textContent='项目已创建，正在打开可恢复 Gate';$('project-status').className='ok';await loadProjects();location.href='/m1-gate'}catch(e){$('project-status').textContent=e.message;$('project-status').className='error'}}
async function loadOpportunities(){try{let values=await json('/opportunities');$('opportunities').innerHTML=values.map(value=>`<article class="asset"><strong>${esc(value.title)}</strong><br><small>${esc(value.source_type)} · ${esc(value.source_ref)} · ${esc(value.status)} · observed=${esc(value.observed_at)}</small><p>${esc(value.angle)}</p><small>evidence=${esc(value.evidence_refs.join(', '))}</small></article>`).join('')||'<p class="muted">尚无选题记录。</p>'}catch(e){$('opportunities').textContent=e.message;$('opportunities').className='error'}}
async function saveOpportunity(){let observed=$('opportunity-observed-at').value;let observed_at=observed?new Date(observed).toISOString():new Date().toISOString();let body={source_type:$('opportunity-source-type').value,source_ref:$('opportunity-source-ref').value.trim(),title:$('opportunity-title').value.trim(),observed_at,fit_reason:$('opportunity-fit').value.trim(),angle:$('opportunity-angle').value.trim(),uncertainty:$('opportunity-uncertainty').value.trim()||null,evidence_refs:split($('opportunity-evidence').value)};try{await json('/opportunities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('opportunity-status').textContent='选题已保存并可被 ScenePlan 引用';$('opportunity-status').className='ok';await loadOpportunities()}catch(e){$('opportunity-status').textContent=e.message;$('opportunity-status').className='error'}}
async function runStage(id,type){try{await json(`/assets/${id}/jobs/${type}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idempotency_key:`workspace-${id}-${type}-${Date.now()}`})});await showReadiness({id})}catch(e){let target=document.querySelector(`#readiness-${id}`);if(target)target.textContent=e.message}}
async function showReadiness(asset){try{let readiness=await json(`/assets/${asset.id}/readiness`),labels={imported:'已导入',preprocessed:'预处理',transcript:'转写',visual:'视觉',index:'索引'};let target=document.querySelector(`#readiness-${asset.id}`);if(!target)return;target.innerHTML=Object.entries(readiness.stages).map(([name,stage])=>`${labels[name]||name}：${esc(stage.status)}`).join(' · ')+`<br><button data-run-stage="${asset.id}" data-stage="analyze_asset">重跑预处理</button><button data-run-stage="${asset.id}" data-stage="transcribe_audio">重跑转写</button><button data-run-stage="${asset.id}" data-stage="index_clips">重跑视觉/索引</button>`;target.querySelectorAll('button[data-run-stage]').forEach(button=>button.onclick=()=>runStage(button.dataset.runStage,button.dataset.stage))}catch(e){let target=document.querySelector(`#readiness-${asset.id}`);if(target)target.textContent=e.message}}
async function loadAssets(){try{let assets=await json('/assets');$('assets').innerHTML=assets.map(a=>{let usage=a.metadata?.r1_usage||'unknown',identity=a.metadata?.r1_identity||'unknown';return `<article class="asset"><strong>${esc(a.source_file)}</strong><br><small>${a.width}×${a.height} · ${a.duration_ms} ms · source=${esc(a.source_kind)}</small><div id="readiness-${a.id}" class="muted">阶段状态加载中…</div><div class="row"><label>用途<select data-usage="${a.id}"><option value="unknown" ${usage==='unknown'?'selected':''}>暂不使用</option><option value="reference" ${usage==='reference'?'selected':''}>仅参考</option><option value="production" ${usage==='production'?'selected':''}>可用于生产</option></select></label><label>身份<select data-identity="${a.id}"><option value="unknown" ${identity==='unknown'?'selected':''}>未知</option><option value="creator" ${identity==='creator'?'selected':''}>本人形象</option><option value="other" ${identity==='other'?'selected':''}>其他人物</option><option value="none" ${identity==='none'?'selected':''}>无人/辅助画面</option></select></label><button data-save-asset="${a.id}">保存分组</button></div></article>`}).join('')||'<p class="muted">尚无素材。</p>';document.querySelectorAll('button[data-save-asset]').forEach(button=>button.onclick=async()=>{let id=button.dataset.saveAsset;try{await json(`/assets/${id}/usage`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({usage:document.querySelector(`[data-usage="${id}"]`).value,identity:document.querySelector(`[data-identity="${id}"]`).value})});button.textContent='已保存'}catch(e){button.textContent=e.message}});assets.forEach(showReadiness)}catch(e){$('assets').textContent=e.message;$('assets').className='error'}}
async function loadImages(){try{let images=await json('/image-assets');$('image-assets').innerHTML=images.map(image=>`<article class="asset"><strong>${esc(image.source_file)}</strong><br><small>${image.width}×${image.height} · source=${esc(image.source_kind)} · rights=${esc(image.authorization_reference)}</small><br><img src="/image-assets/${image.id}/media" alt="" style="max-width:240px;max-height:160px"></article>`).join('')||'<p class="muted">尚无静态图片。</p>'}catch(e){$('image-assets').textContent=e.message;$('image-assets').className='error'}}
async function loadAudio(){try{let assets=await json('/audio-assets');$('audio-assets').innerHTML=assets.map(audio=>`<article class="asset"><strong>${esc(audio.source_file)}</strong><br><small>${audio.duration_ms} ms · ${audio.sample_rate} Hz · ${audio.channels}ch · ${esc(audio.language||'language unknown')} · rights=${esc(audio.authorization_reference)}</small><br><audio controls src="/audio-assets/${audio.id}/media"></audio></article>`).join('')||'<p class="muted">尚无配音/录音。</p>'}catch(e){$('audio-assets').textContent=e.message;$('audio-assets').className='error'}}
 $('save-profile').onclick=saveProfile;$('import-media').onclick=importMedia;$('scan-inbox').onclick=scanInbox;$('import-images').onclick=importImages;$('import-audio').onclick=importAudio;$('create-project').onclick=createProject;$('save-opportunity').onclick=saveOpportunity;$('refresh-runtime').onclick=loadRuntime;$('save-budget').onclick=saveBudget;loadRuntime();loadBudget();loadProfile();loadProjects();loadAssets();loadImages();loadAudio();loadOpportunities();
</script></body></html>'''


def workspace_page() -> HTMLResponse:
    return HTMLResponse(WORKSPACE_HTML)
