"""Replaceable provider adapters kept outside the Content OS domain contracts."""

from .asr import (
    ASRAuthenticationError,
    ASRConfigurationError,
    ASRConnectionError,
    ASRError,
    ASRHTTPError,
    ASRInputError,
    ASRProvider,
    ASRProviderResponseError,
    ASRRateLimitError,
    ASRTimeout,
    OpenAICompatibleASRProvider,
    TranscriptionResult,
    TranscriptionSegment,
)
from .vision import (
    ClipVisualAnalysis,
    OpenAICompatibleVisionProvider,
    VisionAuthenticationError,
    VisionConfigurationError,
    VisionConnectionError,
    VisionError,
    VisionHTTPError,
    VisionInputError,
    VisionProvider,
    VisionProviderResponseError,
    VisionRateLimitError,
    VisionTimeout,
)

__all__ = [
    "ASRAuthenticationError",
    "ASRConfigurationError",
    "ASRConnectionError",
    "ASRError",
    "ASRHTTPError",
    "ASRInputError",
    "ASRProvider",
    "ASRProviderResponseError",
    "ASRRateLimitError",
    "ASRTimeout",
    "OpenAICompatibleASRProvider",
    "TranscriptionResult",
    "TranscriptionSegment",
    "ClipVisualAnalysis",
    "OpenAICompatibleVisionProvider",
    "VisionAuthenticationError",
    "VisionConfigurationError",
    "VisionConnectionError",
    "VisionError",
    "VisionHTTPError",
    "VisionInputError",
    "VisionProvider",
    "VisionProviderResponseError",
    "VisionRateLimitError",
    "VisionTimeout",
]
